[project]
name = "monitoring"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "asyncio>=4.0.0",
    "eth-abi>=5.2.0",
    "matplotlib>=3.10.8",
    "pandas>=3.0.0",
    "web3>=7.14.1",
    "websockets>=15.0.1",
]
